Repository Handlebars-Net/Handlebars.Net, pull requests merged in 2020-11, with the labels that each got.

#378 Introduce `HelperOptions` Helper and ReturnHelper
  source/Handlebars.Test/HelperTests.cs
  source/Handlebars/BlockHelperOptions.cs
  source/Handlebars/Compiler/Structure/Path/PathInfo.cs
  source/Handlebars/Compiler/Translation/Expression/BlockHelperFunctionBinder.cs
  source/Handlebars/Configuration/PathInfoStore.cs
  source/Handlebars/Features/BuildInHelpersFeature.cs
  source/Handlebars/Handlebars.cs
  source/Handlebars/HandlebarsEnvironment.cs
  source/Handlebars/HelperOptions.cs
  source/Handlebars/Helpers/BlockHelpers/BlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/BlockHelperDescriptorBase.cs
  source/Handlebars/Helpers/BlockHelpers/DelegateBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/DelegateReturnBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/InlineBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/LateBindBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/MissingBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/ReturnBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/WithBlockHelperDescriptor.cs
  source/Handlebars/Helpers/DelegateHelperDescriptor.cs
  source/Handlebars/Helpers/DelegateHelperWithOptionsDescriptor.cs
  source/Handlebars/Helpers/DelegateReturnHelperDescriptor.cs
  source/Handlebars/Helpers/DelegateReturnHelperWithOptionsDescriptor.cs
  source/Handlebars/Helpers/HelperDescriptor.cs
  source/Handlebars/Helpers/HelperDescriptorBase.cs
  source/Handlebars/Helpers/LateBindHelperDescriptor.cs
  source/Handlebars/Helpers/LookupReturnHelperDescriptor.cs
  source/Handlebars/Helpers/MissingHelperDescriptor.cs
  source/Handlebars/Helpers/ReturnHelperDescriptor.cs
  source/Handlebars/IHandlebars.cs
  source/Handlebars/MemberAliasProvider/DelegatedMemberAliasProvider.cs
  source/Handlebars/PathInfoLight.cs
  source/Handlebars/ValueProviders/BlockParamsValues.cs
  source/Handlebars/ValueProviders/DataValues.cs
Labels: breaking change, enhancement, handlebars lang compatibility

#382 Fix whitespace support for partials
  source/Handlebars.Test/PartialTests.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulator.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/BlockAccumulatorContext.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/BlockHelperAccumulatorContext.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/ConditionalBlockAccumulatorContext.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/IteratorBlockAccumulatorContext.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/PartialBlockAccumulatorContext.cs
Labels: bug, merge

#358 Fix syntax for block helpers
  README.md
  source/Handlebars.Test/ReadmeTests.cs
Labels: merge, skip-changelog

#384 Replace `StrongBox<T>` with `Ref<T>`
  source/Handlebars.Test/ClosureBuilderTests.cs
  source/Handlebars/Compiler/ClosureBuilder.cs
  source/Handlebars/Compiler/Translation/Expression/BlockHelperFunctionBinder.cs
  source/Handlebars/Compiler/Translation/Expression/HelperFunctionBinder.cs
  source/Handlebars/Compiler/Translation/Expression/PathBinder.cs
  source/Handlebars/Configuration/HandlebarsConfigurationAdapter.cs
  source/Handlebars/Configuration/ICompiledHandlebarsConfiguration.cs
  source/Handlebars/Features/BuildInHelpersFeature.cs
  source/Handlebars/Features/MissingHelperFeature.cs
  source/Handlebars/Helpers/BlockHelpers/LateBindBlockHelperDescriptor.cs
  source/Handlebars/Helpers/LateBindHelperDescriptor.cs
  source/Handlebars/Runtime/Ref.cs
Labels: chore, merge, skip-changelog

#385 Introduce `Context` type
  .github/auto-merge.yml
  source/Handlebars.Test/BasicIntegrationTests.cs
  source/Handlebars.Test/ClosureBuilderTests.cs
  source/Handlebars.Test/HelperTests.cs
  source/Handlebars/BindingContext.cs
  source/Handlebars/BlockHelperOptions.cs
  source/Handlebars/Compiler/ClosureBuilder.cs
  source/Handlebars/Compiler/Translation/Expression/BlockHelperFunctionBinder.cs
  source/Handlebars/Compiler/Translation/Expression/DeferredSectionBlockHelper.cs
  source/Handlebars/Compiler/Translation/Expression/HelperFunctionBinder.cs
  source/Handlebars/Compiler/Translation/Expression/PathBinder.cs
  source/Handlebars/Compiler/Translation/Expression/SubExpressionVisitor.cs
  source/Handlebars/Configuration/HandlebarsConfiguration.cs
  source/Handlebars/Configuration/HandlebarsConfigurationAdapter.cs
  source/Handlebars/Configuration/ICompiledHandlebarsConfiguration.cs
  source/Handlebars/Context.cs
  source/Handlebars/Features/BuildInHelpersFeature.cs
  source/Handlebars/Features/MissingHelperFeature.cs
  source/Handlebars/Handlebars.cs
  source/Handlebars/HandlebarsEnvironment.cs
  source/Handlebars/HelperOptions.cs
  source/Handlebars/Helpers/BlockHelpers/BlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/BlockHelperDescriptorBase.cs
  source/Handlebars/Helpers/BlockHelpers/DelegateBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/DelegateReturnBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/InlineBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/LateBindBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/MissingBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/ReturnBlockHelperDescriptor.cs
  source/Handlebars/Helpers/BlockHelpers/WithBlockHelperDescriptor.cs
  source/Handlebars/Helpers/DelegateHelperDescriptor.cs
  source/Handlebars/Helpers/DelegateHelperWithOptionsDescriptor.cs
  source/Handlebars/Helpers/DelegateReturnHelperDescriptor.cs
  source/Handlebars/Helpers/DelegateReturnHelperWithOptionsDescriptor.cs
  source/Handlebars/Helpers/HelperDescriptor.cs
  source/Handlebars/Helpers/HelperDescriptorBase.cs
  source/Handlebars/Helpers/HelperExtensions.cs
  source/Handlebars/Helpers/HelperType.cs
  source/Handlebars/Helpers/IHelperDescriptor.cs
  source/Handlebars/Helpers/IHelperResolver.cs
  source/Handlebars/Helpers/LateBindHelperDescriptor.cs
  source/Handlebars/Helpers/LookupReturnHelperDescriptor.cs
  source/Handlebars/Helpers/MissingHelperDescriptor.cs
  source/Handlebars/Helpers/ReturnHelperDescriptor.cs
  source/Handlebars/IHandlebars.cs
  source/Handlebars/IO/PolledStringWriter.cs
  source/Handlebars/Pools/BindingContext.Pool.cs
Labels: breaking change

#356 README.md: Add explicit casting in Handlebars.RegisterHelper
  README.md
  source/Handlebars.Test/ReadmeTests.cs
Labels: merge, skip-changelog

#388 Expose inner interfaces in configuration
  source/Handlebars.Test/Collections/FixedSizeDictionaryTests.cs
  source/Handlebars.Test/SubstringTests.cs
  source/Handlebars/BindingContext.cs
  source/Handlebars/Collections/CascadeIndex.cs
  source/Handlebars/Collections/DictionarySlim.cs
  source/Handlebars/Collections/FixedSizeDictionary.cs
  source/Handlebars/Collections/HashHelper.cs
  source/Handlebars/Collections/IAppendOnlyList.cs
  source/Handlebars/Collections/IIndexed.cs
  source/Handlebars/Collections/IReadOnlyIndexed.cs
  source/Handlebars/Collections/LookupSlim.cs
  source/Handlebars/Collections/ObservableDictionary.cs
  source/Handlebars/Collections/ObservableEvent.cs
  source/Handlebars/Collections/ObservableIndex.cs
  source/Handlebars/Collections/ObservableList.cs
  source/Handlebars/Collections/ObserverBuilder.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/BlockAccumulatorContext.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/ConditionalBlockAccumulatorContext.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/PartialBlockAccumulatorContext.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockParamsConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/HelperConverter.cs
  source/Handlebars/Compiler/Structure/Path/ChainSegment.cs
  source/Handlebars/Compiler/Structure/Path/PathInfo.cs
  source/Handlebars/Compiler/Structure/Path/PathResolver.cs
  source/Handlebars/Compiler/Structure/Path/PathSegment.cs
  source/Handlebars/Compiler/Translation/Expression/BlockHelperFunctionBinder.cs
  source/Handlebars/Compiler/Translation/Expression/HashParameterDictionary.cs
  source/Handlebars/Compiler/Translation/Expression/HelperFunctionBinder.cs
  source/Handlebars/Compiler/Translation/Expression/IteratorBinder.cs
  source/Handlebars/Compiler/Translation/Expression/PathBinder.cs
  source/Handlebars/Configuration/CompileTimeConfiguration.cs
  source/Handlebars/Configuration/HandlebarsConfiguration.cs
  source/Handlebars/Configuration/HandlebarsConfigurationAdapter.cs
  source/Handlebars/Configuration/ICompiledHandlebarsConfiguration.cs
  source/Handlebars/Configuration/PathInfoStore.cs
  source/Handlebars/EqualityComparers/ReferenceEqualityComparer.cs
  source/Handlebars/Extensions/EnumerableExtensions.cs
  source/Handlebars/Extensions/ReaderWriterLockSlimExtensions.cs
  source/Handlebars/Features/DefaultCompilerFeature.cs
  source/Handlebars/Features/MissingHelperFeature.cs
  source/Handlebars/FileSystemPartialTemplateResolver.cs
  source/Handlebars/Handlebars.csproj
  source/Handlebars/Helpers/BlockHelpers/InlineBlockHelperDescriptor.cs
  source/Handlebars/MemberAccessors/ReflectionMemberAccessor.cs
  source/Handlebars/ObjectDescriptors/ObjectDescriptor.cs
  source/Handlebars/ObjectDescriptors/ObjectDescriptorFactory.cs
  source/Handlebars/ObjectDescriptors/ObjectDescriptorProvider.cs
  source/Handlebars/PathInfoLight.cs
  source/Handlebars/Runtime/DeferredValue.cs
  source/Handlebars/Runtime/DisposableContainer.cs
  source/Handlebars/Runtime/GcDeferredValue.cs
  source/Handlebars/StringUtils/Substring.cs
Labels: breaking change, enhancement

#389 Reduce compiler allocations
  source/Handlebars/BindingContext.cs
  source/Handlebars/BlockHelperOptions.cs
  source/Handlebars/Compiler/CompilationContext.cs
  source/Handlebars/Compiler/ExpressionBuilder.cs
  source/Handlebars/Compiler/FunctionBuilder.cs
  source/Handlebars/Compiler/HandlebarsCompiler.cs
  source/Handlebars/Compiler/Lexer/Converter/BlockParamsConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/CommentAndLayoutConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/ExpressionScopeConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/HashParameterConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/HashParametersAccumulator.cs
  source/Handlebars/Compiler/Lexer/Converter/HelperArgumentAccumulator.cs
  source/Handlebars/Compiler/Lexer/Converter/LiteralConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/PartialConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/PathConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/RawHelperAccumulator.cs
  source/Handlebars/Compiler/Lexer/Converter/StaticConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/SubExpressionConverter.cs
  source/Handlebars/Compiler/Lexer/Converter/WhitespaceRemover.cs
  source/Handlebars/Compiler/Translation/Expression/BlockHelperFunctionBinder.cs
  source/Handlebars/Compiler/Translation/Expression/IteratorBinder.cs
  source/Handlebars/Compiler/Translation/Expression/PartialBinder.cs
  source/Handlebars/HandlebarsEnvironment.cs
  source/Handlebars/Pools/BindingContext.Pool.cs
Labels: skip-changelog
