Repository Handlebars-Net/Handlebars.Net, pull requests merged in 2022-03, with the labels that each got.

#504 Last letter cut off when the string starts with the separator
  source/Handlebars.Test/IssueTests.cs
  source/Handlebars.Test/SubstringTests.cs
  source/Handlebars/StringUtils/Substring.cs
Labels: bug

#509 Update readme.md to include extra projects
  README.md
Labels: doc

#510 Fix for issue #457
  source/Handlebars.Test/IssueTests.cs
  source/Handlebars/ObjectDescriptors/ObjectDescriptorProvider.cs
Labels: bug

#512 Fix collision handling in`FixedSizeDictionary`
  source/Handlebars.Test/Collections/FixedSizeDictionaryTests.cs
  source/Handlebars/Collections/FixedSizeDictionary.cs
  source/Handlebars/Runtime/AmbientContext.cs
Labels: bug

#514 Introduce `SharedEnvironment`
  README.md
  source/Handlebars.Test/BasicIntegrationTests.cs
  source/Handlebars.Test/Handlebars.Test.csproj
  source/Handlebars.Test/HandlebarsEnvGenerator.cs
  source/Handlebars/Collections/CascadeIndex.cs
  source/Handlebars/Configuration/HandlebarsConfigurationAdapter.cs
  source/Handlebars/EqualityComparers/PathInfoLight.PathInfoLightEqualityComparer.cs
  source/Handlebars/Handlebars.cs
  source/Handlebars/HandlebarsEnvironment.cs
  source/Handlebars/IHandlebars.cs
  source/Handlebars/PathInfoLight.cs
Labels: feature
