Repository Handlebars-Net/Handlebars.Net, pull requests merged in 2024-04, with the labels that each got.

#552 Introduce PartialRecursionDepthLimit
  source/Handlebars.Test/InlinePartialTests.cs
  source/Handlebars.Test/PartialTests.cs
  source/Handlebars/BindingContext.cs
  source/Handlebars/Compiler/Translation/Expression/PartialBinder.cs
  source/Handlebars/Configuration/HandlebarsConfiguration.cs
  source/Handlebars/Configuration/HandlebarsConfigurationAdapter.cs
  source/Handlebars/Configuration/ICompiledHandlebarsConfiguration.cs
  source/Handlebars/Pools/BindingContext.Pool.cs
Labels: bug

#576 Fix/ci
  .github/workflows/ci.yml
  .github/workflows/pull_request.yml
Labels: chore

#570 Add EmbedUntrackedSources
  source/Handlebars/Handlebars.csproj
Labels: enhancement

#578 Update of TFM & dependency optimisation
  .github/workflows/ci.yml
  .github/workflows/pull_request.yml
  .github/workflows/release.yml
  source/Handlebars.Test/DynamicTests.cs
  source/Handlebars.Test/Handlebars.Test.csproj
  source/Handlebars/Collections/ImmutableStack.cs
  source/Handlebars/Handlebars.csproj
  source/Handlebars/IO/EncodedTextWriter.cs
  source/Handlebars/Polyfills/AsyncLocal.cs
Labels: chore
